baseURL = 'https://harry-turner.com/'
languageCode = 'en-us'
title = 'Harry Turner - Portfolio'
theme = "hugo-noir"

[params]
  name = "Harry Turner"
  location = "London, United Kingdom"
  description = "Data analyst & journalist. I turn complex data into compelling stories." 
  profile_image = "/images/your-profile.jpg" # Place in your site's static/images/
  # Social links
  github = "https://github.com/TurnerHaa"
  twitter = "https://www.twitter.com/turnerhaaa"
  twitter_username = "turnerhaaa"
  medium = "https://medium.com/@Ora-kle"
  linkedin = "https://www.linkedin.com/in/harry-turner-436120144/"
  linkedin_username = "Harry Turner"
  email = "harryturnerbath@gmail.com"
  discord = "totemking"

  [params.tech]
  row1 = [
    { icon = "devicon-python-plain", name = "Python" },
    { icon = "devicon-go-plain", name = "Go" },
    { icon = "devicon-javascript-plain", name = "JavaScript" },
    { icon = "devicon-typescript-plain", name = "TypeScript" },
    { icon = "devicon-react-original", name = "React" },
    { icon = "devicon-vuejs-plain", name = "Vue.js" },
    { icon = "devicon-html5-plain", name = "HTML5" },
    { icon = "devicon-css3-plain", name = "CSS3" }
  ]
  row2 = [
    { icon = "devicon-docker-plain", name = "Docker" },
    { icon = "devicon-kubernetes-plain", name = "Kubernetes" },
    { icon = "devicon-nginx-original", name = "Nginx" },
    { icon = "devicon-postgresql-plain", name = "PostgreSQL" },
    { icon = "devicon-redis-plain", name = "Redis" },
    { icon = "devicon-git-plain", name = "Git" },
    { icon = "devicon-hugo-plain", name = "Hugo" },
    { icon = "devicon-tailwindcss-plain", name = "TailwindCSS" }
  ]

# Experience
[[params.experience]]
company = "Beyond Words Studio"
role = "Data Analyst & Journalist"
period = "Oct 2023 - Present"
logo = "/images/company/lorem.png"
description = "Data and editorial lead on dashboards, executive reports and websites for clients like Boeing, Netflix, BCG."
responsibilities = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    "Ut enim ad minim veniam, quis nostrud exercitation",
    "Duis aute irure dolor in reprehenderit in voluptate",
    "Excepteur sint occaecat cupidatat non proident"
]

[[params.experience]]
company = "Beyond Words Studio"
role = "Junior Data Analyst & Journalist"
period = "Dec 2021 - Oct 2023"
logo = "/images/company/ipsum.png"
description = "Data and editorial for clients like Google, Design Museum and WHO. Guest lecturer on MA Design for Data at LCC."
responsibilities = [
    "Sed ut perspiciatis unde omnis iste natus error",
    "Nemo enim ipsam voluptatem quia voluptas sit",
    "At vero eos et accusamus et iusto odio dignissimos",
    "Et harum quidem rerum facilis est et expedita"
]

[[params.experience]]
company = "Beyond Words Studio"
role = "Editorial Intern"
period = "Oct 2021 - Dec 2021"
logo = "/images/company/dolor.png"
description = "Ran social media for the head of Data, Analytics and Delivery for Impact at WHO."
responsibilities = [
    "Nam libero tempore, cum soluta nobis est eligendi",
    "Temporibus autem quibusdam et aut officiis debitis",
    "Itaque earum rerum hic tenetur a sapiente delectus"
]


# Projects
[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "R, Google Sheets, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "R, Google Sheets, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "R, Google Sheets, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "R, Google Sheets, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "R, Google Sheets, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "RETESTER"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"


[[params.blogs]]
title = "Lorem Ipsum Systems"
date = "2025-03-15"
summary = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem."
tags = ["Lorem", "Ipsum", "Dolor"]
content = """
Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit...
"""
link = "https://medium.com/@loremipsum/lorem-systems"

[[params.blogs]]
title = "The Future of Dolor"
date = "2025-02-28"
summary = "At vero eos et accusamus et iusto odio dignissimos ducimus."
tags = ["Sit", "Amet", "Consectetur"]
content = """
Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis...
"""
link = "https://medium.com/@loremipsum/future-dolor"

[[params.blogs]]
title = "Adipiscing: A Practical Guide"
date = "2025-02-10"
summary = "Nam libero tempore, cum soluta nobis est eligendi optio."
tags = ["Elit", "Tempor", "Guide"]
content = """
Et harum quidem rerum facilis est et expedita distinctio...
"""
link = "https://medium.com/@loremipsum/adipiscing-guide"

[[params.blogs]]
title = "Optimizing Incididunt"
date = "2025-01-20"
summary = "Temporibus autem quibusdam et aut officiis debitis."
tags = ["Labore", "Dolore", "Magna"]
content = """
Itaque earum rerum hic tenetur a sapiente delectus...
"""
link = "https://medium.com/@loremipsum/optimizing-incididunt"

[[params.blogs]]
title = "Aliqua: A Comprehensive Guide"
date = "2024-12-15"
summary = "Quis autem vel eum iure reprehenderit qui in ea voluptate."
tags = ["Ut", "Enim", "Minim"]
content = """
Nisi ut aliquid ex ea commodi consequatur quis autem...
"""
link = "https://medium.com/@loremipsum/aliqua-guide"

[[params.blogs]]
title = "Veniam in Practice"
date = "2024-11-20"
summary = "Duis aute irure dolor in reprehenderit in voluptate velit."
tags = ["Esse", "Cillum", "Dolore"]
content = """
Excepteur sint occaecat cupidatat non proident...
"""
link = "https://medium.com/@loremipsum/veniam-practice"

[[params.blogs]]
title = "Fugiat for Systems"
date = "2024-10-25"
summary = "Sunt in culpa qui officia deserunt mollit anim id est laborum."
tags = ["Nulla", "Pariatur", "Systems"]
content = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit...
"""
link = "https://medium.com/@loremipsum/fugiat-systems"

[[params.blogs]]
title = "Best Practices in Consectetur"
date = "2024-09-30"
summary = "Sed do eiusmod tempor incididunt ut labore et dolore magna."
tags = ["Best", "Practices", "Guide"]
content = """
Ut enim ad minim veniam, quis nostrud exercitation...
"""
link = "https://medium.com/@loremipsum/consectetur-practices"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Contact me"
    url = "/contact/"
    weight = 4